spring:
  datasource:
     url: jdbc:h2:mem:test 
     username: sa
  mvc:
      hiddenmethod:
        filter:
          enabled: true
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*"

      
  jpa:
    show-sql: true
    hibernate: 
        ddl-auto: none
       
  h2:
    console:
      enabled: true
      path: /konsola-h2

  liquibase:
    change-log: classpath:db/master.xml
    enabled: true

