spring:
  datasource:
     url: jdbc:h2:mem:test 
     username: sa
  mvc:
      hiddenmethod:
        filter:
          enabled: true
  

  jpa:
    show-sql: true
    hibernate: 
        ddl-auto: none
  h2:
    console:
      enabled: true
      path: /konsola-h2

  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
    
logging:
  level:
  #  org.springframework.web: DEBUG
    org.springframework.security: DEBUG

 


